/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthStartRouteImport } from './routes/auth.start'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ConsoleSettingsRouteImport } from './routes/_console.settings'
import { Route as ConsoleMembersRouteImport } from './routes/_console.members'
import { Route as ConsoleAppsRouteImport } from './routes/_console.apps'
import { Route as ConsoleAppsIndexRouteImport } from './routes/_console.apps.index'
import { Route as ApiServerRuntimeSdkKeysRouteImport } from './routes/api.server.runtime-sdk-keys'
import { Route as ApiServerProductsRouteImport } from './routes/api.server.products'
import { Route as ApiServerOfferingsRouteImport } from './routes/api.server.offerings'
import { Route as ApiServerCustomerInfoRouteImport } from './routes/api.server.customer-info'
import { Route as ApiRuntimeOfferingsRouteImport } from './routes/api.runtime.offerings'
import { Route as ApiRuntimeCustomerInfoRouteImport } from './routes/api.runtime.customer-info'
import { Route as ConsoleTenantSlugAppSlugRouteImport } from './routes/_console.$tenantSlug.$appSlug'
import { Route as ConsoleTenantSlugAppSlugIndexRouteImport } from './routes/_console.$tenantSlug.$appSlug.index'
import { Route as ApiServerEntitlementsCheckRouteImport } from './routes/api.server.entitlements.check'
import { Route as ApiRuntimeIapReconcileRouteImport } from './routes/api.runtime.iap.reconcile'
import { Route as ApiRuntimeEntitlementsCheckRouteImport } from './routes/api.runtime.entitlements.check'
import { Route as ConsoleTenantSlugAppSlugStoresRouteImport } from './routes/_console.$tenantSlug.$appSlug.stores'
import { Route as ConsoleTenantSlugAppSlugSettingsRouteImport } from './routes/_console.$tenantSlug.$appSlug.settings'
import { Route as ConsoleTenantSlugAppSlugProductsRouteImport } from './routes/_console.$tenantSlug.$appSlug.products'
import { Route as ConsoleTenantSlugAppSlugOfferingsRouteImport } from './routes/_console.$tenantSlug.$appSlug.offerings'
import { Route as ConsoleTenantSlugAppSlugEntitlementsRouteImport } from './routes/_console.$tenantSlug.$appSlug.entitlements'
import { Route as ConsoleTenantSlugAppSlugAppUsersRouteImport } from './routes/_console.$tenantSlug.$appSlug.app-users'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMembersRoute = ConsoleMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsRoute = ConsoleAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsIndexRoute = ConsoleAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleAppsRoute,
} as any)
const ApiServerRuntimeSdkKeysRoute = ApiServerRuntimeSdkKeysRouteImport.update({
  id: '/api/server/runtime-sdk-keys',
  path: '/api/server/runtime-sdk-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerProductsRoute = ApiServerProductsRouteImport.update({
  id: '/api/server/products',
  path: '/api/server/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerOfferingsRoute = ApiServerOfferingsRouteImport.update({
  id: '/api/server/offerings',
  path: '/api/server/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServerCustomerInfoRoute = ApiServerCustomerInfoRouteImport.update({
  id: '/api/server/customer-info',
  path: '/api/server/customer-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeOfferingsRoute = ApiRuntimeOfferingsRouteImport.update({
  id: '/api/runtime/offerings',
  path: '/api/runtime/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeCustomerInfoRoute = ApiRuntimeCustomerInfoRouteImport.update({
  id: '/api/runtime/customer-info',
  path: '/api/runtime/customer-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTenantSlugAppSlugRoute =
  ConsoleTenantSlugAppSlugRouteImport.update({
    id: '/$tenantSlug/$appSlug',
    path: '/$tenantSlug/$appSlug',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleTenantSlugAppSlugIndexRoute =
  ConsoleTenantSlugAppSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConsoleTenantSlugAppSlugRoute,
  } as any)
const ApiServerEntitlementsCheckRoute =
  ApiServerEntitlementsCheckRouteImport.update({
    id: '/api/server/entitlements/check',
    path: '/api/server/entitlements/check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRuntimeIapReconcileRoute = ApiRuntimeIapReconcileRouteImport.update({
  id: '/api/runtime/iap/reconcile',
  path: '/api/runtime/iap/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeEntitlementsCheckRoute =
  ApiRuntimeEntitlementsCheckRouteImport.update({
    id: '/api/runtime/entitlements/check',
    path: '/api/runtime/entitlements/check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsoleTenantSlugAppSlugStoresRoute =
  ConsoleTenantSlugAppSlugStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => ConsoleTenantSlugAppSlugRoute,
  } as any)
const ConsoleTenantSlugAppSlugSettingsRoute =
  ConsoleTenantSlugAppSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ConsoleTenantSlugAppSlugRoute,
  } as any)
const ConsoleTenantSlugAppSlugProductsRoute =
  ConsoleTenantSlugAppSlugProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ConsoleTenantSlugAppSlugRoute,
  } as any)
const ConsoleTenantSlugAppSlugOfferingsRoute =
  ConsoleTenantSlugAppSlugOfferingsRouteImport.update({
    id: '/offerings',
    path: '/offerings',
    getParentRoute: () => ConsoleTenantSlugAppSlugRoute,
  } as any)
const ConsoleTenantSlugAppSlugEntitlementsRoute =
  ConsoleTenantSlugAppSlugEntitlementsRouteImport.update({
    id: '/entitlements',
    path: '/entitlements',
    getParentRoute: () => ConsoleTenantSlugAppSlugRoute,
  } as any)
const ConsoleTenantSlugAppSlugAppUsersRoute =
  ConsoleTenantSlugAppSlugAppUsersRouteImport.update({
    id: '/app-users',
    path: '/app-users',
    getParentRoute: () => ConsoleTenantSlugAppSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/apps': typeof ConsoleAppsRouteWithChildren
  '/members': typeof ConsoleMembersRoute
  '/settings': typeof ConsoleSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/$tenantSlug/$appSlug': typeof ConsoleTenantSlugAppSlugRouteWithChildren
  '/api/runtime/customer-info': typeof ApiRuntimeCustomerInfoRoute
  '/api/runtime/offerings': typeof ApiRuntimeOfferingsRoute
  '/api/server/customer-info': typeof ApiServerCustomerInfoRoute
  '/api/server/offerings': typeof ApiServerOfferingsRoute
  '/api/server/products': typeof ApiServerProductsRoute
  '/api/server/runtime-sdk-keys': typeof ApiServerRuntimeSdkKeysRoute
  '/apps/': typeof ConsoleAppsIndexRoute
  '/$tenantSlug/$appSlug/app-users': typeof ConsoleTenantSlugAppSlugAppUsersRoute
  '/$tenantSlug/$appSlug/entitlements': typeof ConsoleTenantSlugAppSlugEntitlementsRoute
  '/$tenantSlug/$appSlug/offerings': typeof ConsoleTenantSlugAppSlugOfferingsRoute
  '/$tenantSlug/$appSlug/products': typeof ConsoleTenantSlugAppSlugProductsRoute
  '/$tenantSlug/$appSlug/settings': typeof ConsoleTenantSlugAppSlugSettingsRoute
  '/$tenantSlug/$appSlug/stores': typeof ConsoleTenantSlugAppSlugStoresRoute
  '/api/runtime/entitlements/check': typeof ApiRuntimeEntitlementsCheckRoute
  '/api/runtime/iap/reconcile': typeof ApiRuntimeIapReconcileRoute
  '/api/server/entitlements/check': typeof ApiServerEntitlementsCheckRoute
  '/$tenantSlug/$appSlug/': typeof ConsoleTenantSlugAppSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/members': typeof ConsoleMembersRoute
  '/settings': typeof ConsoleSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/api/runtime/customer-info': typeof ApiRuntimeCustomerInfoRoute
  '/api/runtime/offerings': typeof ApiRuntimeOfferingsRoute
  '/api/server/customer-info': typeof ApiServerCustomerInfoRoute
  '/api/server/offerings': typeof ApiServerOfferingsRoute
  '/api/server/products': typeof ApiServerProductsRoute
  '/api/server/runtime-sdk-keys': typeof ApiServerRuntimeSdkKeysRoute
  '/apps': typeof ConsoleAppsIndexRoute
  '/$tenantSlug/$appSlug/app-users': typeof ConsoleTenantSlugAppSlugAppUsersRoute
  '/$tenantSlug/$appSlug/entitlements': typeof ConsoleTenantSlugAppSlugEntitlementsRoute
  '/$tenantSlug/$appSlug/offerings': typeof ConsoleTenantSlugAppSlugOfferingsRoute
  '/$tenantSlug/$appSlug/products': typeof ConsoleTenantSlugAppSlugProductsRoute
  '/$tenantSlug/$appSlug/settings': typeof ConsoleTenantSlugAppSlugSettingsRoute
  '/$tenantSlug/$appSlug/stores': typeof ConsoleTenantSlugAppSlugStoresRoute
  '/api/runtime/entitlements/check': typeof ApiRuntimeEntitlementsCheckRoute
  '/api/runtime/iap/reconcile': typeof ApiRuntimeIapReconcileRoute
  '/api/server/entitlements/check': typeof ApiServerEntitlementsCheckRoute
  '/$tenantSlug/$appSlug': typeof ConsoleTenantSlugAppSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_console/apps': typeof ConsoleAppsRouteWithChildren
  '/_console/members': typeof ConsoleMembersRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/_console/$tenantSlug/$appSlug': typeof ConsoleTenantSlugAppSlugRouteWithChildren
  '/api/runtime/customer-info': typeof ApiRuntimeCustomerInfoRoute
  '/api/runtime/offerings': typeof ApiRuntimeOfferingsRoute
  '/api/server/customer-info': typeof ApiServerCustomerInfoRoute
  '/api/server/offerings': typeof ApiServerOfferingsRoute
  '/api/server/products': typeof ApiServerProductsRoute
  '/api/server/runtime-sdk-keys': typeof ApiServerRuntimeSdkKeysRoute
  '/_console/apps/': typeof ConsoleAppsIndexRoute
  '/_console/$tenantSlug/$appSlug/app-users': typeof ConsoleTenantSlugAppSlugAppUsersRoute
  '/_console/$tenantSlug/$appSlug/entitlements': typeof ConsoleTenantSlugAppSlugEntitlementsRoute
  '/_console/$tenantSlug/$appSlug/offerings': typeof ConsoleTenantSlugAppSlugOfferingsRoute
  '/_console/$tenantSlug/$appSlug/products': typeof ConsoleTenantSlugAppSlugProductsRoute
  '/_console/$tenantSlug/$appSlug/settings': typeof ConsoleTenantSlugAppSlugSettingsRoute
  '/_console/$tenantSlug/$appSlug/stores': typeof ConsoleTenantSlugAppSlugStoresRoute
  '/api/runtime/entitlements/check': typeof ApiRuntimeEntitlementsCheckRoute
  '/api/runtime/iap/reconcile': typeof ApiRuntimeIapReconcileRoute
  '/api/server/entitlements/check': typeof ApiServerEntitlementsCheckRoute
  '/_console/$tenantSlug/$appSlug/': typeof ConsoleTenantSlugAppSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/apps'
    | '/members'
    | '/settings'
    | '/auth/callback'
    | '/auth/start'
    | '/$tenantSlug/$appSlug'
    | '/api/runtime/customer-info'
    | '/api/runtime/offerings'
    | '/api/server/customer-info'
    | '/api/server/offerings'
    | '/api/server/products'
    | '/api/server/runtime-sdk-keys'
    | '/apps/'
    | '/$tenantSlug/$appSlug/app-users'
    | '/$tenantSlug/$appSlug/entitlements'
    | '/$tenantSlug/$appSlug/offerings'
    | '/$tenantSlug/$appSlug/products'
    | '/$tenantSlug/$appSlug/settings'
    | '/$tenantSlug/$appSlug/stores'
    | '/api/runtime/entitlements/check'
    | '/api/runtime/iap/reconcile'
    | '/api/server/entitlements/check'
    | '/$tenantSlug/$appSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/members'
    | '/settings'
    | '/auth/callback'
    | '/auth/start'
    | '/api/runtime/customer-info'
    | '/api/runtime/offerings'
    | '/api/server/customer-info'
    | '/api/server/offerings'
    | '/api/server/products'
    | '/api/server/runtime-sdk-keys'
    | '/apps'
    | '/$tenantSlug/$appSlug/app-users'
    | '/$tenantSlug/$appSlug/entitlements'
    | '/$tenantSlug/$appSlug/offerings'
    | '/$tenantSlug/$appSlug/products'
    | '/$tenantSlug/$appSlug/settings'
    | '/$tenantSlug/$appSlug/stores'
    | '/api/runtime/entitlements/check'
    | '/api/runtime/iap/reconcile'
    | '/api/server/entitlements/check'
    | '/$tenantSlug/$appSlug'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/login'
    | '/logout'
    | '/_console/apps'
    | '/_console/members'
    | '/_console/settings'
    | '/auth/callback'
    | '/auth/start'
    | '/_console/$tenantSlug/$appSlug'
    | '/api/runtime/customer-info'
    | '/api/runtime/offerings'
    | '/api/server/customer-info'
    | '/api/server/offerings'
    | '/api/server/products'
    | '/api/server/runtime-sdk-keys'
    | '/_console/apps/'
    | '/_console/$tenantSlug/$appSlug/app-users'
    | '/_console/$tenantSlug/$appSlug/entitlements'
    | '/_console/$tenantSlug/$appSlug/offerings'
    | '/_console/$tenantSlug/$appSlug/products'
    | '/_console/$tenantSlug/$appSlug/settings'
    | '/_console/$tenantSlug/$appSlug/stores'
    | '/api/runtime/entitlements/check'
    | '/api/runtime/iap/reconcile'
    | '/api/server/entitlements/check'
    | '/_console/$tenantSlug/$appSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStartRoute: typeof AuthStartRoute
  ApiRuntimeCustomerInfoRoute: typeof ApiRuntimeCustomerInfoRoute
  ApiRuntimeOfferingsRoute: typeof ApiRuntimeOfferingsRoute
  ApiServerCustomerInfoRoute: typeof ApiServerCustomerInfoRoute
  ApiServerOfferingsRoute: typeof ApiServerOfferingsRoute
  ApiServerProductsRoute: typeof ApiServerProductsRoute
  ApiServerRuntimeSdkKeysRoute: typeof ApiServerRuntimeSdkKeysRoute
  ApiRuntimeEntitlementsCheckRoute: typeof ApiRuntimeEntitlementsCheckRoute
  ApiRuntimeIapReconcileRoute: typeof ApiRuntimeIapReconcileRoute
  ApiServerEntitlementsCheckRoute: typeof ApiServerEntitlementsCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/members': {
      id: '/_console/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof ConsoleMembersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/apps': {
      id: '/_console/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof ConsoleAppsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/apps/': {
      id: '/_console/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof ConsoleAppsIndexRouteImport
      parentRoute: typeof ConsoleAppsRoute
    }
    '/api/server/runtime-sdk-keys': {
      id: '/api/server/runtime-sdk-keys'
      path: '/api/server/runtime-sdk-keys'
      fullPath: '/api/server/runtime-sdk-keys'
      preLoaderRoute: typeof ApiServerRuntimeSdkKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/products': {
      id: '/api/server/products'
      path: '/api/server/products'
      fullPath: '/api/server/products'
      preLoaderRoute: typeof ApiServerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/offerings': {
      id: '/api/server/offerings'
      path: '/api/server/offerings'
      fullPath: '/api/server/offerings'
      preLoaderRoute: typeof ApiServerOfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/server/customer-info': {
      id: '/api/server/customer-info'
      path: '/api/server/customer-info'
      fullPath: '/api/server/customer-info'
      preLoaderRoute: typeof ApiServerCustomerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/offerings': {
      id: '/api/runtime/offerings'
      path: '/api/runtime/offerings'
      fullPath: '/api/runtime/offerings'
      preLoaderRoute: typeof ApiRuntimeOfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/customer-info': {
      id: '/api/runtime/customer-info'
      path: '/api/runtime/customer-info'
      fullPath: '/api/runtime/customer-info'
      preLoaderRoute: typeof ApiRuntimeCustomerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/$tenantSlug/$appSlug': {
      id: '/_console/$tenantSlug/$appSlug'
      path: '/$tenantSlug/$appSlug'
      fullPath: '/$tenantSlug/$appSlug'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/$tenantSlug/$appSlug/': {
      id: '/_console/$tenantSlug/$appSlug/'
      path: '/'
      fullPath: '/$tenantSlug/$appSlug/'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugIndexRouteImport
      parentRoute: typeof ConsoleTenantSlugAppSlugRoute
    }
    '/api/server/entitlements/check': {
      id: '/api/server/entitlements/check'
      path: '/api/server/entitlements/check'
      fullPath: '/api/server/entitlements/check'
      preLoaderRoute: typeof ApiServerEntitlementsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/iap/reconcile': {
      id: '/api/runtime/iap/reconcile'
      path: '/api/runtime/iap/reconcile'
      fullPath: '/api/runtime/iap/reconcile'
      preLoaderRoute: typeof ApiRuntimeIapReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/entitlements/check': {
      id: '/api/runtime/entitlements/check'
      path: '/api/runtime/entitlements/check'
      fullPath: '/api/runtime/entitlements/check'
      preLoaderRoute: typeof ApiRuntimeEntitlementsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/$tenantSlug/$appSlug/stores': {
      id: '/_console/$tenantSlug/$appSlug/stores'
      path: '/stores'
      fullPath: '/$tenantSlug/$appSlug/stores'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugStoresRouteImport
      parentRoute: typeof ConsoleTenantSlugAppSlugRoute
    }
    '/_console/$tenantSlug/$appSlug/settings': {
      id: '/_console/$tenantSlug/$appSlug/settings'
      path: '/settings'
      fullPath: '/$tenantSlug/$appSlug/settings'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugSettingsRouteImport
      parentRoute: typeof ConsoleTenantSlugAppSlugRoute
    }
    '/_console/$tenantSlug/$appSlug/products': {
      id: '/_console/$tenantSlug/$appSlug/products'
      path: '/products'
      fullPath: '/$tenantSlug/$appSlug/products'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugProductsRouteImport
      parentRoute: typeof ConsoleTenantSlugAppSlugRoute
    }
    '/_console/$tenantSlug/$appSlug/offerings': {
      id: '/_console/$tenantSlug/$appSlug/offerings'
      path: '/offerings'
      fullPath: '/$tenantSlug/$appSlug/offerings'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugOfferingsRouteImport
      parentRoute: typeof ConsoleTenantSlugAppSlugRoute
    }
    '/_console/$tenantSlug/$appSlug/entitlements': {
      id: '/_console/$tenantSlug/$appSlug/entitlements'
      path: '/entitlements'
      fullPath: '/$tenantSlug/$appSlug/entitlements'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugEntitlementsRouteImport
      parentRoute: typeof ConsoleTenantSlugAppSlugRoute
    }
    '/_console/$tenantSlug/$appSlug/app-users': {
      id: '/_console/$tenantSlug/$appSlug/app-users'
      path: '/app-users'
      fullPath: '/$tenantSlug/$appSlug/app-users'
      preLoaderRoute: typeof ConsoleTenantSlugAppSlugAppUsersRouteImport
      parentRoute: typeof ConsoleTenantSlugAppSlugRoute
    }
  }
}

interface ConsoleAppsRouteChildren {
  ConsoleAppsIndexRoute: typeof ConsoleAppsIndexRoute
}

const ConsoleAppsRouteChildren: ConsoleAppsRouteChildren = {
  ConsoleAppsIndexRoute: ConsoleAppsIndexRoute,
}

const ConsoleAppsRouteWithChildren = ConsoleAppsRoute._addFileChildren(
  ConsoleAppsRouteChildren,
)

interface ConsoleTenantSlugAppSlugRouteChildren {
  ConsoleTenantSlugAppSlugAppUsersRoute: typeof ConsoleTenantSlugAppSlugAppUsersRoute
  ConsoleTenantSlugAppSlugEntitlementsRoute: typeof ConsoleTenantSlugAppSlugEntitlementsRoute
  ConsoleTenantSlugAppSlugOfferingsRoute: typeof ConsoleTenantSlugAppSlugOfferingsRoute
  ConsoleTenantSlugAppSlugProductsRoute: typeof ConsoleTenantSlugAppSlugProductsRoute
  ConsoleTenantSlugAppSlugSettingsRoute: typeof ConsoleTenantSlugAppSlugSettingsRoute
  ConsoleTenantSlugAppSlugStoresRoute: typeof ConsoleTenantSlugAppSlugStoresRoute
  ConsoleTenantSlugAppSlugIndexRoute: typeof ConsoleTenantSlugAppSlugIndexRoute
}

const ConsoleTenantSlugAppSlugRouteChildren: ConsoleTenantSlugAppSlugRouteChildren =
  {
    ConsoleTenantSlugAppSlugAppUsersRoute:
      ConsoleTenantSlugAppSlugAppUsersRoute,
    ConsoleTenantSlugAppSlugEntitlementsRoute:
      ConsoleTenantSlugAppSlugEntitlementsRoute,
    ConsoleTenantSlugAppSlugOfferingsRoute:
      ConsoleTenantSlugAppSlugOfferingsRoute,
    ConsoleTenantSlugAppSlugProductsRoute:
      ConsoleTenantSlugAppSlugProductsRoute,
    ConsoleTenantSlugAppSlugSettingsRoute:
      ConsoleTenantSlugAppSlugSettingsRoute,
    ConsoleTenantSlugAppSlugStoresRoute: ConsoleTenantSlugAppSlugStoresRoute,
    ConsoleTenantSlugAppSlugIndexRoute: ConsoleTenantSlugAppSlugIndexRoute,
  }

const ConsoleTenantSlugAppSlugRouteWithChildren =
  ConsoleTenantSlugAppSlugRoute._addFileChildren(
    ConsoleTenantSlugAppSlugRouteChildren,
  )

interface ConsoleRouteChildren {
  ConsoleAppsRoute: typeof ConsoleAppsRouteWithChildren
  ConsoleMembersRoute: typeof ConsoleMembersRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleTenantSlugAppSlugRoute: typeof ConsoleTenantSlugAppSlugRouteWithChildren
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAppsRoute: ConsoleAppsRouteWithChildren,
  ConsoleMembersRoute: ConsoleMembersRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleTenantSlugAppSlugRoute: ConsoleTenantSlugAppSlugRouteWithChildren,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStartRoute: AuthStartRoute,
  ApiRuntimeCustomerInfoRoute: ApiRuntimeCustomerInfoRoute,
  ApiRuntimeOfferingsRoute: ApiRuntimeOfferingsRoute,
  ApiServerCustomerInfoRoute: ApiServerCustomerInfoRoute,
  ApiServerOfferingsRoute: ApiServerOfferingsRoute,
  ApiServerProductsRoute: ApiServerProductsRoute,
  ApiServerRuntimeSdkKeysRoute: ApiServerRuntimeSdkKeysRoute,
  ApiRuntimeEntitlementsCheckRoute: ApiRuntimeEntitlementsCheckRoute,
  ApiRuntimeIapReconcileRoute: ApiRuntimeIapReconcileRoute,
  ApiServerEntitlementsCheckRoute: ApiServerEntitlementsCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
